@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDQxODI5NTJ9._W25rTs_7yb6yy0k3sByYbYjz1lRBDcdPXZ8r_O6g60

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Posts index
GET http://localhost:3000/posts

### Posts create
POST http://localhost:3000/posts
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Test title",
  "body": "Test body"
}

### Posts show
GET http://localhost:3000/posts/1.json

### Posts update
PATCH http://localhost:3000/posts/10
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "image": "test"
}

### Posts destroy
DELETE http://localhost:3000/posts/10
Authorization: Bearer {{jwt}}
